### ISSUE TITLE
No response returned for some cves

### ISSUE THREAD

**Issue by Silentsoul04** [ransomsec/cvePuller#1]
Hi, nice first tool!

I found an issue when using it first time, Some cve quesries doesn't return description output.

### Command:

cvePuller --cve day -all

### error output 

<*>---------------------------------------------------------<*>

CVE ID 9: CVE-2022-2080
DESCRIPTION: <nil>
ASSIGNER: <nil>
SEVERITY: <nil>

<*>---------------------------------------------------------<*>

CVE ID 10: CVE-2022-2034
DESCRIPTION: <nil>
ASSIGNER: <nil>
SEVERITY: <nil>

I haven't properly looked at api response but my guess is, it is either due to incorrect parsing of json or issue with cvetrend api.

**Comment by ransomsec** [comment]
Hi, Thank you for your creating first request. ;)

This is not an actual issue, because cvetrends dosen't provide any information about specific CVE-ID, for example in your case `CVE-2022-2080` doesn't provide any info except CVE number meaning that `CVETRENDS` not provide any info about `CVE-2022-2080`. If cvetrends not provide any info `cvePuller` mark as `<nil>`.

References:
[CVE-Trends](https://cvetrends.com/api/cves/24hrs) go to number 9 for `CVE-2022-2080`
[CVE-Report](https://cve.report/CVE-2022-2080) See no information published about `CVE-2022-2080`

**Same as all CVEs**

*See Description, Assigner, Severity*
![no-cve-info-provided](https://user-images.githubusercontent.com/83533000/182993770-7c42c5d0-7389-41e1-b2a8-c3fbe2f9a63f.png)
